name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.2.2
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          export GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no"
          cd /home/ubuntu/flask-app
          echo "GIT PULL:"
          git pull
          sudo systemctl restart flask-app
          echo "ESTADO DEL SERVICIO flask-app:"
          sudo systemctl status flask-app --no-pager